### ISSUE TITLE
RFE: Support configuring datadog as a data source using `keptn configure monitoring datadog`

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#15]
**Problem statement.**
As a user I would like to be able to configure datadog as a [datasource in lighthouse](https://github.com/keptn/keptn/tree/master/lighthouse-service#configuring-a-data-source) using `keptn configure monitoring datadog`

**Describe the solution you'd like**
Above command should create the ConfigMap that lighthouse needs for setting up the datasource. Right now we have to create the ConfigMap manually like this:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: lighthouse-config-<project-name>
  namespace: keptn
data:
  sli-provider: "datadog"
```

**Describe alternatives you've considered**
Creating it by hand is one of the alternatives. We use it now but as a user I don't want to create the ConfigMap by hand every time. 

**Additional context**
Needs more info here
